### ISSUE TITLE
creating a optimization problem with SHOT

### ISSUE THREAD

**Issue by jbensabat** [coin-or/SHOT#144]
Hello 
I managed to build SHOT with (IPOPT, CBC) under windows  MSVC and Intel Fortran.
I ran the examples with the OSIL format and it seems that it works.
I would like now to create a real problem and I see that doing so with OSIL is challenging because of the syntax and the apparent lack of documentation. 
What could be the simplest way to create a problem ? using AMPL ? 
Is there a way to create an OSIL file with a suitable programming (with expressions and a suitable parser) ?
thanks 
jac

**Comment by andreaslundell** [comment]
There are some options for creating models for SHOT, instructions at https://shotsolver.dev/shot/using-shot/getting-started.
- Use Pyomo in Python (https://github.com/Pyomo/pyomo)
- Use JuMP in Julia (https://github.com/jump-dev/JuMP.jl)
- Use GAMS (http://www.gams.com).

It is also possible to create the problem using SHOT's API in C++, instruction at https://github.com/coin-or/SHOT/blob/e225a002500a4826d8dd575799bf3486967d57f1/test/ModelTest.cpp

OSiL is unfortunately not a really good language for creating optimization models, and I do not really know of any software that can create this type of format. GAMS can convert to OSiL format using its CONVERT "solver" https://www.gams.com/34/docs/S_CONVERT.html.

If you have any further questions, please reopen this issue.

**Comment by jbensabat** [comment]
hi 
thanks 
will try either with ampl or hard-coding then
