### ISSUE TITLE
Description of Model.Reformulation.Constraint.PartitionNonlinearTerms option

### ISSUE THREAD

**Issue by ZedongPeng** [coin-or/SHOT#146]
On the [SHOT homepage](https://shotsolver.dev/shot/using-shot/solver-options#automatic-reformulations), the description of `Model.Reformulation.Constraint.PartitionNonlinearTerms` and `Model.Reformulation.ObjectiveFunction.PartitionNonlinearTerms` are both 

> When to partition nonlinear sums in objective function

This also happens to `Model.Reformulation.Constraint.PartitionQuadraticTerms` and `Model.Reformulation.ObjectiveFunction.PartitionQuadraticTerms`. Is this correct? I thought `Model.Reformulation.Constraint.PartitionNonlinearTerms` means **When to partition nonlinear sums in constraints**.

**Comment by andreaslundell** [comment]
Thank you for noticing. This has now been fixed in the documentation, c.f. https://github.com/coin-or/SHOT/commit/e6ea79fce86771ae8beefc7e7f2aed4e1e2f7acf, and on the website.
