### ISSUE TITLE
How can I specify solver options in Pyomo?

### ISSUE THREAD

**Issue by damdaepark** [coin-or/SHOT#148]
Couldn't find a solution to specify solver options in Pyomo on the [documentation](https://shotsolver.dev/shot/using-shot/getting-started).

Does anyone know how to?

**Comment by chemrgineer** [comment]
You can pass solver options two way. 
If you specify few options:
```
from pyomo.environ import *
solver = SolverFactory("SHOT")
solver.options["Subsolver.Ipopt.LinearSolver"] = 4
solver.options["Subsolver.Ipopt.MaxIterations"] = 3e3
```
------------------------------------------------------------
Alternative method, you can create option file and pass to solver.
`solver.options["--opt"]="SHOT.opt" `
here SHOT.opt file contains your options.
All options and explanations is here: https://shotsolver.dev/shot/using-shot/solver-options

**Comment by damdaepark** [comment]
Thank you @chemrgineer. How about specifying MIP solver then?

**Comment by damdaepark** [comment]
Thank you @chemrgineer.
