### ISSUE TITLE
cannot create std::vector larger than max_size()

### ISSUE THREAD

**Issue by svigerske** [coin-or/SHOT#161]
When running with Gurobi on lop97ic.gms or lop97icx.gms, there seems to be a problem to get the solution back from Gurobi into SHOT:
```
[...]
Explored 1937 nodes (46593 simplex iterations) in 0.74 seconds (0.69 work units)
Thread count was 8 (of 8 available processors)

Solution count 10: 4099.06 4122.87 4137.48 ... 4417.51

Optimal solution found (tolerance 1.00e-04)
Best objective 4.099059953600e+03, best bound 4.099059953600e+03, gap 0.0000%

User-callback calls 4455, time in user-callback 0.00 sec
Error when solving problem: cannot create std::vector larger than max_size()
```
I get this with the current SHOT master, but also versions from half a year ago.

**Comment by andreaslundell** [comment]
Cannot reproduce this either, SHOT from the command line solves both problems with Gurobi.

What Gurobi version are you using (I am using 9.5.1 build v9.5.1rc2 (linux64))?

**Comment by svigerske** [comment]
9.5.2 build v9.5.2rc0

I don't have access to a system with Gurobi license today, unfortunately.

**Comment by svigerske** [comment]
Seems to be caused by mismatch between Gurobi header and lib on our side (#160), too.
Sorry to take your time.
