### ISSUE TITLE
Cbc with multiple threads

### ISSUE THREAD

**Issue by andreaslundell** [coin-or/SHOT#20]
Just checking @svigerske, can you run SHOT with Cbc with multiple threads? The standalone binary of Cbc can solve the same problem when read from an LP-file, but when I solve it through SHOT it just runs one thread... 

The same seems to happen when I use Cbc using its interactive shell... I would assume Cbc is very picky with how the different arguments are given to it.

**Comment by svigerske** [comment]
Maybe try putting -solve to the end of the argument list; otherwise it probably first solves and then sets the options.
