### ISSUE TITLE
MIPSolver initializeProblem return ignored in constructor

### ISSUE THREAD

**Issue by svigerske** [coin-or/SHOT#32]
If the MIP solver could not be initialized, `initializeProblem` returns false, but this bool is not checked in the constructor of the MIP solver classes. At least for Cplex and Gurobi this seems to be the case.
So when not having a Gurobi license, I get a decent error message, but then a segfault:
```
        Error when initializing problem:: "No Gurobi license found (...)"

Program received signal SIGSEGV, Segmentation fault.
0x00007fffefca8186 in GRBModel::addVar(double, double, double, char, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
```

**Comment by andreaslundell** [comment]
Should be fixed in https://github.com/coin-or/SHOT/tree/issue-32.

**Comment by svigerske** [comment]
Yes, thank you. I now get a beautiful
```
...
  - Bounds for 32 variables tightened in 0.01 s.
        Error when initializing problem:: "No Gurobi license found (***)"
 Cannot initialize solver: Cannot initialize selected MIP solver.
 Error when initializing problem.
--- Restarting execution
--- waterx.gms(164) 2 Mb
--- Reading solution for model network
*** Status: Normal completion
```

**Comment by andreaslundell** [comment]
Well I could perhaps condense the output a little bit further. Three "initializes" in one error message is perhaps two too many :)
