### ISSUE TITLE
GAMS installation scripts

### ISSUE THREAD

**Issue by andreaslundell** [coin-or/SHOT#56]
Will the GAMS installation scripts work in the future if there is already a solver named SHOT in GAMS? Or is it simply to change "SHOT" in the scripts to something unique?

**Comment by svigerske** [comment]
That would then overwrite the SHOT that comes with GAMS.
Replacing SHOT by something else in the lines starting at https://github.com/coin-or/SHOT/blob/master/misc/gamsinst.sh#L53 should allow to have two versions of SHOT simultaneously.

I also started a new version of the scripts here:
- https://github.com/coin-or/GAMSlinks/blob/master/gamsinst.py
- https://github.com/coin-or/GAMSlinks/blob/master/gamsuninst.py
Maybe they are easier to use or reuse.
They don't touch other libs in GAMS as in https://github.com/coin-or/SHOT/blob/master/misc/gamsinst.sh#L117, but that doesn't seem to be a clean solution anyway.

With GAMS 31, though, there might be a way to make a solver known to GAMS without editing files in the GAMS system dir.

**Comment by svigerske** [comment]
What you want me to do here? Rename SHOT in `misc/gamsinst.sh`, upgrade to new scripts, or wait for GAMS 31 and provide new instructions on how to tell GAMS about SHOT?

**Comment by andreaslundell** [comment]
I am not really sure myself... Will it work with the new scripts and GAMS 30 or older? What about all the license checks that you do now, are those backwards compatible as well? Or should we just require GAMS 31+?

**Comment by svigerske** [comment]
The new scripts work with GAMS 30 and older, too.

The license checks require GAMS >= 30, because there was some big change including the pal API in GAMS 30.

The easiest would be to remove all scripts and explain which file in GAMS to edit in which way. And when GAMS 31 is out, add an explanation for the new alternative.

I doubt that there will be many that want to install SHOT in GAMS when GAMS already includes a more-or-less recent SHOT version.

**Comment by andreaslundell** [comment]
Yes, I agree. The only person using those scripts would probably be me :)

**Comment by svigerske** [comment]
So https://github.com/coin-or/SHOT/pull/new/gamsinst is removing the scripts.

Can you merge this, if you agree, and add the information from
https://github.com/coin-or/SHOT/blob/0955259e4817d9c9569394c630c3b6fe38fba2bd/INSTALL#L79
to https://shotsolver.dev/shot/about-shot/compiling ?
