### ISSUE TITLE
Anti epigraph reformulation

### ISSUE THREAD

**Issue by andreaslundell** [coin-or/SHOT#93]
GAMS is sometimes not able to extract the objective function from an epigraph constraint (e.g. smallinvSN*). 

SHOT should then extract this itself.

**Comment by andreaslundell** [comment]
I guess there is some reason why this is not done automatically in GAMS @svigerske? 😄

**Comment by svigerske** [comment]
I wouldn't use "reason" and "GAMS" together in a sentence too carelessly :).

For some reason, GAMS ;) only reformulates the objective variable out if the "objective-equation" is of `=E=` type (and the objective variable is unbounded continuous and appears in only one equation and does so linearly). So nothing will happen for a `=L=` or `=G=` equation. Maybe someone thought that it would be bad if solutions feasible but non-optimal for the non-reformulated problem could have a different objective function value when evaluated in the reformulated problem. Or it has something to do with dual solution and mapping them.

It makes sense to have this reformulation in SHOT also for non-GAMS users, though.

**Comment by andreaslundell** [comment]
Yes, I agree... This would also fix an issue I have with unbounded MIP subproblems before cuts for the objective constraint have been added to the linear outer approximation.

**Comment by andreaslundell** [comment]
Fixes as of #110
